# Site settings
author: Ivana Dokic
title: Why Software Engineering
header-img: img/home-bg.png
email: ivana_pile@yahoo.com
copyright_name: Ivana Dokic
description: > # this means to ignore newlines until "baseurl:"
  I am not growing if I am not challenged
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ivanadokic

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
